apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# uncommeting below reosources will not load the app and will also delete it from the cluster. This is used as an hard reset.
  - linkding
  #- audiobookshelf